const User = require('./user')
const BailDefense = require('./bail-defense')
const BailJudge = require('./bail-judge')
const BailProsecution = require('./bail-prosecution')
const Bail = require('./bail')
const CaseResolution = require('./case-resolution')
const Case = require('./case')
const Charge = require('./charge')
const CourtRoom = require('./courtroom')
const Defendant = require('./defendant')
const Judge = require('./judge')
const PleaDiscussion = require('./plea-discussion')

Defendant.belongsTo(Case)
Case.hasOne(Defendant)

//has stores in target -- belongs to stores in source
Judge.hasMany(Case)
CourtRoom.hasMany(Case)
Charge.hasOne(Case)
PleaDiscussion.hasOne(Case)
CaseResolution.hasOne(Case)

BailDefense.hasOne(Bail)
BailProsecution.hasOne(Bail)
BailJudge.hasOne(Bail)
Bail.hasOne(Case)
